### ISSUE TITLE
3 [Vault] Add Tests in TODO

### ISSUE THREAD

**Issue by esteblock** [paltalabs/defindex#288]
- [x] test::vault::deposit_and_invest::one_asset_several_strategies
- [x] test::vault::deposit_and_invest::deposit_simple_then_deposit_and_invest
- [x] test::vault::get_asset_amounts_per_shares::deposit_and_invest_several_assets_get_asset_amounts_per_shares
- [x] test::vault::withdraw::from_strategies_one_asset_two_strategies_success
- [x] test::vault::withdraw::from_strategy_success_no_mock_all_auths
- [x] test::vault::initialize::with_one_asset_and_several_strategies

**Comment by chopan123** [comment]
- [ ]  test::vault::invest::one_asset_several_strategies
